### ISSUE TITLE
Add scss usage standards to documentation

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-element#48]
In there should be things like:
- Configurable styles
- @fontface
- global settings
- slots

**Comment by jurekbarth** [comment]
For compatibility reason it would we nice if you could mention that if you have a component named `my-button` and your markup looks something like this:

```
this.render`
<style>
  .my-button {
     display: flex;
  }
</style>
<div class="my-button">
  Something
</div>
`
```

IE11 and i think Edge as well will display these styles, because it's polyfills sets some classes and IE11 then treats the style tag as a normal html element.
